### PR TITLE
Group#5_FurtherResearch

### PR DESCRIPTION
**Pull request by nbabirye**
This is Najuma working in class on the HIVE portion
CGC will be completed by @ECL314 and @nramnarine.

### CODE REVIEW

**Comment by ECL314** [comment]
The assignment was updated to include the information for the CGC part of the assignment.

**Comment by nramnarine** [comment]
Ready for Review
[Group#5_FurtherResearch.txt](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/files/3720102/Group.5_FurtherResearch.txt)

**Comment by jpat1546** [comment]
@nbabirye @ECL314 @nramnarine Great job using Github to work through this assignment! Take a look @ this assignment's [README](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/Further%20research%20documents/README.md), and please make sure you've followed all the instructions. 

I'm okay with the list of tools not being in paragraph form. **However, I'm unsure if the email portion of this assignment was done, as there's no clear text in this document stating it was.** If the emails were sent out that's great, but I would advise including a paragraph to this document summarizing what you did- something like "We evaluated how feasible it would be to reproduce this analysis in two cloud-based platforms: CGC, and HIVE.  An email has been sent to HIVE Platform and CGC's points of contact with the the respective tools not found in their platform as feedback"

If the emails weren't sent out yet, I recommend adding the WIP tag to this and removing me from the assignee until they are.

Thanks!

**Comment by nbabirye** [comment]
Hi, @jpat1546 we @ECL314 @nramnarine uploaded and attached a text file. The description is just a space we used for notes. Thanks. 

https://github.com/biocompute-objects/GW-SMHS-BIOC6223/pull/84#issuecomment-541275161

**Comment by jpat1546** [comment]
@nbabirye Ok, that works. Would you mind modifying your group's [md file](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/Further%20research%20documents/Group5%20%5BWIP%5D.md) submitted to the Further Research documents folder? That will be the document used for your submission! Thanks

**Comment by nbabirye** [comment]
@jpat1546, are we just removing the guide notes and changing the description to ready for review?

**Comment by jpat1546** [comment]
@nbabirye If you'd like to keep the guide notes (tools/descriptions) you have there, you can. I've put that under a "notes" section in your [md](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/Further%20research%20documents/Group5%20%5BWIP%5D.md). You can place your submission text under "Further Research Group 5" section I created in the md. (202d4ac)

**Pull request merged**
