### PR TITLE
Update Turkey_Alsaeedy_BCO_000520.json

### PR DESCRIPTION
**Pull request by Turkeyalsaeedy**
I have fixed it, could you review it again?

### CODE REVIEW

**Review by jpat1546 — APPROVED** [review]
### Your BCO has been approved.

Great job fixing all your assigned issues, @Turkeyalsaeedy !

Prior to submitting to the pFDA challenge, please make the following 2 changes to your BCO in the BCO editor (then download from there and submit to the pFDA):

In Provenance Domain:

- Change reviewer status from "in-review" to "approved"
- Change reviewer_comment from "Reviewed by BioCompute technical assistant, approved pending modification by author" to "Reviewed and approved by BioCompute technical assistant."

Leave me a comment below if these instructions are not clear. Thanks!

**Comment by Turkeyalsaeedy** [comment]
Done! Thank you, you have been incredibly helpful!

**Comment by jpat1546** [comment]
@Turkeyalsaeedy 
You're welcome! Please be sure to change the review status and reviewer comment before submitting to the pFDA challenge.

**Comment by Turkeyalsaeedy** [comment]
Sure I have done that, 

Actually, I have a question regards the pFDA submission
There are "Name this submission" and the description.
What do I suppose to write my name or the paper's tile?  

Could you please tell me!

**Pull request merged**
