### PR TITLE
Create XiyingDing

### PR DESCRIPTION
**Pull request by xzd5071**

### CODE REVIEW

**Comment by jpat1546** [comment]
Please follow the instructions to:
1. Create a Project (See [README](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/README.md))
2. Please modify your Pull Request to include the assignee, labels, project, and milestone tags found on https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/docs/3_DraftBCO.md 

Thank you!

**Comment by xzd5071** [comment]
Hello Janisha,
I still cannot create the project so can you check if I have the authority
or is there any other problem? My github id is xzd5071. Also, I see this
notification after uploading BCO and I wonder if this is normal or I need
to do anything.
[image: image.png]
Yours
Xiying Ding

Janisha Patel <notifications@github.com> 于2019年10月7日周一 下午6:36写道：

**Comment by jpat1546** [comment]
@xzd5071 As you are a member of the "Students" Team, you should have full permissions to create a project. Let's try this: 
1. Go to https://github.com/biocompute-objects/GW-SMHS-BIOC6223/projects
2. Screenshot the page you see and attach below. Thanks!


(also, your BCO screenshot in the previous comment did not upload correctly- you may need to try again)

Thanks!

**Comment by xzd5071** [comment]
I am now a member.

**Pull request closed without merging**
