### PR TITLE
Maybe Final BCO

### PR DESCRIPTION
**Pull request by besheajj**
I had changed all authors to BOTH "authoredBy" and "derivedFrom" as stated in #113:

"The authors of the publication must be included in the contributor section. Please add them and set their contribution type to both "authoredBy" and “derivedFrom”."

### CODE REVIEW

**Comment by jpat1546** [comment]
The last pull request for this BCO (#235) did not have both contribution types listed for the authors.  Glad to see this request #239 does.

**Review by jpat1546 — APPROVED** [review]
### Your BCO is approved

All your assigned issues have been fixed, @besheajj .

Prior to submitting to the pFDA challenge, please make the following 2 changes to your BCO in the BCO Editor (then download and submit to the pFDA):
In Provenance domain:

- Change reviewer status from "in review" to "approved"
- Change reviewer_comment from "Reviewed by BioCompute technical assistant, approval pending modification by author" to "Reviewed and approved by BioCompute technical assistant"

Leave me a comment if these instructions are not clear. Thanks.

**Comment by besheajj** [comment]
Thank you so much @jpat1546 you have been patient and helpful this entire time.

**Comment by jpat1546** [comment]
You are welcome @besheajj . Please remember to change the **reviewer status** and **reviewer comment** before submitting to the pFDA BCO challenge!

**Pull request merged**
